-- ============================================================
-- D-Sign Module: Database Migration V1
-- Creates DSIGN_CERTIFICATE and DSIGN_AUDIT_LOG tables
-- Oracle SQL conventions (VARCHAR2, TIMESTAMP, CLOB, sequences)
-- ============================================================

-- Certificate table for storing registered digital certificates
CREATE TABLE DSIGN_CERTIFICATE (
    CERT_REF_ID     VARCHAR2(64)    NOT NULL,
    SUBJECT         VARCHAR2(512),
    ISSUER          VARCHAR2(512),
    SERIAL_NUMBER   VARCHAR2(128),
    NOT_BEFORE      TIMESTAMP,
    NOT_AFTER       TIMESTAMP,
    PUBLIC_KEY      CLOB,
    KEY_REFERENCE   VARCHAR2(256),
    OWNER_ID        VARCHAR2(128),
    CA_PROVIDER     VARCHAR2(64),
    STATUS          VARCHAR2(20)    NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_DSIGN_CERTIFICATE PRIMARY KEY (CERT_REF_ID)
);

-- Indexes for common query patterns
CREATE INDEX IDX_DSIGN_CERT_OWNER ON DSIGN_CERTIFICATE (OWNER_ID);
CREATE INDEX IDX_DSIGN_CERT_STATUS ON DSIGN_CERTIFICATE (STATUS);
CREATE INDEX IDX_DSIGN_CERT_SERIAL ON DSIGN_CERTIFICATE (SERIAL_NUMBER);

-- Sequence for audit log auto-generated IDs
CREATE SEQUENCE DSIGN_AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Audit log table for persistent storage of all D-Sign operations
CREATE TABLE DSIGN_AUDIT_LOG (
    ID              NUMBER(19)      NOT NULL,
    CORRELATION_ID  VARCHAR2(64)    NOT NULL,
    SIGNER_ID       VARCHAR2(128),
    CERTIFICATE_REF VARCHAR2(64),
    ALGORITHM       VARCHAR2(64),
    OPERATION_TYPE  VARCHAR2(20)    NOT NULL,
    RESULT          VARCHAR2(20)    NOT NULL,
    FAILED_STEP     VARCHAR2(128),
    ERROR_CODE      VARCHAR2(64),
    ERROR_MESSAGE   CLOB,
    TIMESTAMP       TIMESTAMP       NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    CONSTRAINT PK_DSIGN_AUDIT_LOG PRIMARY KEY (ID)
);

-- Indexes for audit log query patterns
CREATE INDEX IDX_DSIGN_AUDIT_CORR ON DSIGN_AUDIT_LOG (CORRELATION_ID);
CREATE INDEX IDX_DSIGN_AUDIT_SIGNER ON DSIGN_AUDIT_LOG (SIGNER_ID);
CREATE INDEX IDX_DSIGN_AUDIT_OP_TYPE ON DSIGN_AUDIT_LOG (OPERATION_TYPE);
CREATE INDEX IDX_DSIGN_AUDIT_TIMESTAMP ON DSIGN_AUDIT_LOG (TIMESTAMP);
