-- QR Code History Table
CREATE TABLE QR_CODE_HISTORY (
    ID              VARCHAR2(36)    NOT NULL,
    QR_TYPE         VARCHAR2(50)    NOT NULL,
    CONTENT         CLOB            NOT NULL,
    IMAGE_BASE64    CLOB,
    STATUS          VARCHAR2(20)    NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(100),
    CONSTRAINT PK_QR_CODE_HISTORY PRIMARY KEY (ID)
);

CREATE INDEX IDX_QR_CODE_HISTORY_TYPE ON QR_CODE_HISTORY(QR_TYPE);
CREATE INDEX IDX_QR_CODE_HISTORY_CREATED ON QR_CODE_HISTORY(CREATED_AT);

-- QR Parse History Table
CREATE TABLE QR_PARSE_HISTORY (
    ID              VARCHAR2(36)    NOT NULL,
    RAW_CONTENT     CLOB            NOT NULL,
    QR_TYPE         VARCHAR2(50),
    PARSED_DATA     CLOB,
    STATUS          VARCHAR2(20)    NOT NULL,
    ERROR_MESSAGE   VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(100),
    CONSTRAINT PK_QR_PARSE_HISTORY PRIMARY KEY (ID)
);

CREATE INDEX IDX_QR_PARSE_HISTORY_TYPE ON QR_PARSE_HISTORY(QR_TYPE);
CREATE INDEX IDX_QR_PARSE_HISTORY_CREATED ON QR_PARSE_HISTORY(CREATED_AT);

-- VietQR Info Table (lưu thông tin VietQR đã tạo)
CREATE TABLE VIET_QR_INFO (
    ID                  VARCHAR2(36)    NOT NULL,
    QR_CODE_ID          VARCHAR2(36)    NOT NULL,
    BANK_BIN            VARCHAR2(10)    NOT NULL,
    BANK_ACCOUNT        VARCHAR2(50)    NOT NULL,
    ACCOUNT_NAME        VARCHAR2(200),
    AMOUNT              NUMBER(18,2),
    DESCRIPTION         VARCHAR2(500),
    TRANSACTION_REF     VARCHAR2(100),
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_VIET_QR_INFO PRIMARY KEY (ID),
    CONSTRAINT FK_VIET_QR_QR_CODE FOREIGN KEY (QR_CODE_ID) REFERENCES QR_CODE_HISTORY(ID)
);

CREATE INDEX IDX_VIET_QR_BANK_ACCOUNT ON VIET_QR_INFO(BANK_ACCOUNT);
CREATE INDEX IDX_VIET_QR_CODE_ID ON VIET_QR_INFO(QR_CODE_ID);
